image: node:alpine

build-job:
  stage: build
  script:
    - npm install -g --unsafe-perm elm
    - elm make src/Main.elm

pages:
  stage: deploy
  script:
    - npm install -g --unsafe-perm elm
    - elm make src/Main.elm --optimize --output=public/index.html
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
