image: node:alpine

build-job:
  stage: build
  script:
    - npm install -g --unsafe-perm elm
    - elm make src/Main.elm

test-job:
  stage: test
  script:
    - npm install -g --unsafe-perm elm
    - npm install -g --unsafe-perm elm-test
    - elm-test

lint-job:
  stage: test
  script:
    - npm install -g --unsafe-perm elm
    - npm install -g --unsafe-perm elm-review
    - elm-review --template jfmengels/elm-review-unused/example
  allow_failure: true

pages:
  stage: deploy
  script:
    - npm install -g --unsafe-perm elm
    - elm make src/Main.elm --optimize --output=public/index.html
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
