image: node:alpine

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm/

before_script:
  - npm ci --cache .npm --prefer-offline

build-job:
  stage: build
  script:
    - npx elm make src/Main.elm

test-job:
  stage: test
  script:
    - npx elm-test

lint-job:
  stage: test
  script:
    - npx elm-review
  allow_failure: true

pages:
  stage: deploy
  script:
    - npx elm make src/Main.elm --optimize --output=public/index.html
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
